modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/supermassimo/DynamicTrees-ExC/issues"

[[mods]]
modId="dtquark"
version="${file.jarVersion}"
displayName="Dynamic Trees for Quark"

updateJSONURL="https://github.com/supermassimo/DynamicTrees-ExC/blob/1.12.2/.DONE/DynamicTrees-Quark/version_info.json?raw=true"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-quark"

authors="Max Hyper" #optional
description='''
Compatibility Mod between Dynamic trees and Quark
'''
[[dependencies.dtquark]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtquark]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtquark]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[0.10.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtquark]]
    modId="dynamictreesplus"
    mandatory=false
    versionRange="[0.1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtquark]]
    modId="quark"
    mandatory=true
    versionRange="[r2.4-312,)"
    ordering="AFTER"
    side="BOTH"
