# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="MIT"

# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://github.com/supermassimo/DynamicTrees-ExC/issues" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="dttconstruct" #mandatory

# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="${file.jarVersion}" #mandatory

# A display name for the mod
displayName="Dynamic Trees for Tinkers' Construct" #mandatory

# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://github.com/supermassimo/DynamicTrees-ExC/blob/1.12.2/.DONE/DynamicTrees-Quark/version_info.json?raw=true" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-quark" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="" #optional

# A text field displayed in the mod UI
credits="" #optional

# A text field displayed in the mod UI
authors="Max Hyper" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
Compatibility Mod between Dynamic trees and Tinkers' Construct
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.dttconstruct]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dttconstruct]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dttconstruct]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[0.10.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dttconstruct]]
    modId="dynamictreesplus"
    mandatory=false
    versionRange="[0.1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dttconstruct]]
    modId="tconstruct"
    mandatory=true
    versionRange="[3.0.3,)"
    ordering="AFTER"
    side="BOTH"
